# Generated by Django 5.2.5 on 2025-09-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('is_dead', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('categories', models.ManyToManyField(blank=True, related_name='authors', to='categories.category')),
            ],
        ),
    ]
